# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatDemo
  pod 'SwiftProtobuf'
  pod 'SwiftSocket'
  pod 'GzipSwift'
  
  
  target 'ChatDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
